#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 7777

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Debug
WORKDIR /src
COPY ["MatchServer/MatchServer.csproj", "MatchServer/"]
COPY ["ServerShared/ServerShared.csproj", "ServerShared/"]
COPY ["Server/DBMigrations/DBMigrations.csproj", "Server/DBMigrations/"]
COPY ["Shared/Shared.csproj", "Shared/"]
RUN dotnet restore "./MatchServer/./MatchServer.csproj"
COPY . .
WORKDIR "/src/MatchServer"
RUN dotnet build "./MatchServer.csproj" -p:BuildMode=TEST -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Debug
RUN dotnet publish "./MatchServer.csproj" -p:BuildMode=TEST -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MatchServer.dll"]